### ISSUE TITLE
Show some dynamic content being served

### ISSUE THREAD

**Issue by Ivshti** [Stremio/stremio-express-addon-example#1]
it would be cool to show something dynamic, otherwise we're kind of missing the point of express

also wouldn't it be more understandable if we just generated the content in the express code? I mean just have the JSON in there

also this I'm thinking should be a separate example: https://github.com/Stremio/stremio-addon-sdk/issues/15

**Comment by jaruba** [comment]
Uhm, I'm thinking of changing the name of this repo to `stremio-express-static-addon` and mentioning it in `stremio-static-addon-example` as a way to use the local machine as the server.

Then make a separate repo for an Express example with dynamic content.

**Comment by jaruba** [comment]
Changed the repo name to `stremio-express-static-addon`, it is now mentioned in the `Readme.md` of `stremio-static-addon-example` as an example of how to use that repo with a Node.js Express Server and also a demo for using `localtunnel` with it.

Reference:
https://github.com/Stremio/stremio-static-addon-example/blob/master/README.md

I'll make 2 new repos, one for dynamic content with Express and another to show usage of Proxy Add-ons.
